#!/usr/bin/env bash
# Register a client in DAPS without using the UI
# This directly modifies the DAPS configuration files

set -e

CLIENT_ID="${1}"
CLIENT_NAME="${2:-Test Client}"
CLIENT_SECRET="${3:-test-secret-123}"

echo "=========================================="
echo "DAPS Client Registration (No UI Required)"
echo "=========================================="
echo ""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

if [ -z "$CLIENT_ID" ]; then
    echo "Usage: $0 <client_id> [client_name] [client_secret]"
    echo ""
    echo "Example:"
    echo "  $0 test-client \"My Test Client\" my-secret-123"
    echo ""
    echo "Or to use connector's SKI as client ID:"

    if [ -f "conf/default-connector-keystore.p12" ]; then
        CERT_SKI=$(keytool -list -v -keystore conf/default-connector-keystore.p12 -storepass password 2>/dev/null | \
            grep -A1 "SubjectKeyIdentifier" | tail -1 | tr -d ' :' | tr '[:upper:]' '[:lower:]')

        if [ ! -z "$CERT_SKI" ]; then
            echo "  $0 $CERT_SKI \"My Connector\""
        fi
    fi

    exit 1
fi

echo "Client ID: $CLIENT_ID"
echo "Client Name: $CLIENT_NAME"
echo "Client Secret: $CLIENT_SECRET"
echo ""

# Check if clients.yml exists
if [ ! -f "config/clients.yml" ]; then
    echo -e "${YELLOW}⚠ config/clients.yml not found${NC}"
    echo "Creating new clients.yml file..."
    mkdir -p config
    cat > config/clients.yml <<EOF
---
# DAPS Clients Configuration
# Generated by register-daps-client.sh

EOF
fi

# Check if client already exists
if grep -q "client_id: $CLIENT_ID" config/clients.yml 2>/dev/null; then
    echo -e "${YELLOW}⚠ Client $CLIENT_ID already exists in config/clients.yml${NC}"
    echo ""
    echo "Existing configuration:"
    grep -A 20 "client_id: $CLIENT_ID" config/clients.yml | head -20
    echo ""
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi

    # Remove existing entry (simple approach - backup first)
    cp config/clients.yml config/clients.yml.backup
    echo -e "${BLUE}ℹ Backup created: config/clients.yml.backup${NC}"
fi

# Create backup
cp config/clients.yml config/clients.yml.backup.$(date +%s) 2>/dev/null || true

# Add new client entry
echo -e "${BLUE}Adding client to config/clients.yml...${NC}"

cat >> config/clients.yml <<EOF

- client_id: $CLIENT_ID
  client_name: $CLIENT_NAME
  grant_types:
    - client_credentials
  token_endpoint_auth_method: client_secret_basic
  scope:
    - idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
    - key: idsc
      value: IDS_CONNECTOR_ATTRIBUTES_ALL
    - key: securityProfile
      value: idsc:BASE_SECURITY_PROFILE
  metadata:
    client_secret: $CLIENT_SECRET
EOF

echo -e "${GREEN}✓ Client added to config/clients.yml${NC}"
echo ""

# Verify the addition
echo "New client configuration:"
grep -A 20 "client_id: $CLIENT_ID" config/clients.yml | head -20

echo ""
echo ""

# Restart DAPS to pick up changes
echo "=========================================="
echo "Restarting DAPS"
echo "=========================================="
echo ""

echo "DAPS needs to be restarted to load the new client configuration..."
echo ""

if command -v docker &> /dev/null; then
    echo -e "${BLUE}Restarting DAPS container...${NC}"
    docker compose restart daps

    echo ""
    echo "Waiting for DAPS to start..."
    sleep 5

    # Check if DAPS is responding
    DAPS_HTTP=$(curl -k -s -o /dev/null -w "%{http_code}" https://localhost/auth/jwks.json 2>/dev/null || echo "000")

    if [ "$DAPS_HTTP" = "200" ]; then
        echo -e "${GREEN}✓ DAPS is running${NC}"
    else
        echo -e "${YELLOW}⚠ DAPS may still be starting up (HTTP $DAPS_HTTP)${NC}"
        echo "Wait a few seconds and try again"
    fi
else
    echo -e "${YELLOW}⚠ Docker not found in this environment${NC}"
    echo "Please restart DAPS manually:"
    echo "  docker compose restart daps"
fi

echo ""
echo ""

# Test token acquisition
echo "=========================================="
echo "Testing Token Acquisition"
echo "=========================================="
echo ""

echo "Attempting to get a token with the new client credentials..."
echo ""

sleep 2  # Give DAPS a moment

TOKEN_RESPONSE=$(curl -k -s -X POST https://localhost/auth/token \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=client_credentials" \
    -d "client_id=$CLIENT_ID" \
    -d "client_secret=$CLIENT_SECRET" \
    -d "scope=idsc:IDS_CONNECTOR_ATTRIBUTES_ALL" 2>&1)

TOKEN_HTTP=$(curl -k -s -o /dev/null -w "%{http_code}" -X POST https://localhost/auth/token \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=client_credentials" \
    -d "client_id=$CLIENT_ID" \
    -d "client_secret=$CLIENT_SECRET" \
    -d "scope=idsc:IDS_CONNECTOR_ATTRIBUTES_ALL")

if [ "$TOKEN_HTTP" = "200" ]; then
    echo -e "${GREEN}✓✓✓ SUCCESS! Token obtained${NC}"
    echo ""
    echo "Response:"
    echo "$TOKEN_RESPONSE" | jq '.' 2>/dev/null || echo "$TOKEN_RESPONSE"

    # Extract and save token
    ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token' 2>/dev/null)

    if [ ! -z "$ACCESS_TOKEN" ] && [ "$ACCESS_TOKEN" != "null" ]; then
        echo ""
        echo -e "${GREEN}Access Token:${NC}"
        echo "$ACCESS_TOKEN"

        # Save to file
        echo "$ACCESS_TOKEN" > /tmp/daps-token.txt
        echo ""
        echo "Token saved to: /tmp/daps-token.txt"
        echo ""

        # Provide test commands
        echo -e "${GREEN}Test the token:${NC}"
        echo ""
        echo "curl -k -H \"Authorization: Bearer \$(cat /tmp/daps-token.txt)\" \\"
        echo "  https://localhost:8081/api/offers"
        echo ""
        echo "Or:"
        echo ""
        echo "curl -k -H \"Authorization: Bearer $ACCESS_TOKEN\" \\"
        echo "  https://localhost:8081/api/offers"
    fi
else
    echo -e "${YELLOW}⚠ Token request returned HTTP $TOKEN_HTTP${NC}"
    echo ""
    echo "Response:"
    echo "$TOKEN_RESPONSE"
    echo ""
    echo "This might be normal if:"
    echo "  - DAPS is still restarting"
    echo "  - DAPS requires different authentication method"
    echo "  - Configuration format is different"
    echo ""
    echo "Check DAPS logs:"
    echo "  docker compose logs daps | tail -50"
fi

echo ""
echo ""

echo "=========================================="
echo "Summary"
echo "=========================================="
echo ""
echo "Client registered:"
echo "  Client ID: $CLIENT_ID"
echo "  Client Secret: $CLIENT_SECRET"
echo "  Scopes: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL"
echo ""
echo "Configuration file: config/clients.yml"
echo "Backup created: config/clients.yml.backup.*"
echo ""
echo "To request a token manually:"
echo ""
echo "curl -k -X POST https://localhost/auth/token \\"
echo "  -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "  -d 'grant_type=client_credentials' \\"
echo "  -d 'client_id=$CLIENT_ID' \\"
echo "  -d 'client_secret=$CLIENT_SECRET' \\"
echo "  -d 'scope=idsc:IDS_CONNECTOR_ATTRIBUTES_ALL'"
echo ""
